import type { Era } from '@/shared/types/timeline';
import type { HistoricalEvent } from '@/shared/types/events';
import type { Location } from '@/shared/types/locations';
import type { Landmark } from '@/shared/types/landmarks';

export const MIN_YEAR = -10000;
export const MAX_YEAR = 2024;

export const ERAS: Era[] = [
  { id: 'prehistory', name: 'Prehistory', startYear: -10000, endYear: -3000, description: 'The dawn of human civilization, from the end of the last Ice Age to the invention of writing.', accentColor: 'var(--color-era-prehistory)' },
  { id: 'ancient', name: 'Ancient World', startYear: -3000, endYear: -500, description: 'The rise of the first great civilizations: Egypt, Mesopotamia, the Indus Valley, and China.', accentColor: 'var(--color-era-ancient)' },
  { id: 'classical', name: 'Classical Antiquity', startYear: -500, endYear: 500, description: 'The age of Greece, Rome, and the great empires that shaped Western civilization.', accentColor: 'var(--color-era-classical)' },
  { id: 'medieval', name: 'Medieval Period', startYear: 500, endYear: 1500, description: 'A millennium of feudalism, crusades, the Islamic Golden Age, and the seeds of the Renaissance.', accentColor: 'var(--color-era-medieval)' },
  { id: 'renaissance', name: 'Renaissance & Exploration', startYear: 1500, endYear: 1800, description: 'An era of artistic rebirth, scientific revolution, and global exploration.', accentColor: 'var(--color-era-renaissance)' },
  { id: 'industrial', name: 'Industrial Age', startYear: 1800, endYear: 1900, description: 'The transformation of society through machinery, steam power, and mass production.', accentColor: 'var(--color-era-industrial)' },
  { id: 'modern', name: 'Modern Era', startYear: 1900, endYear: 2024, description: 'Two world wars, the atomic age, the digital revolution, and globalization.', accentColor: 'var(--color-era-modern)' },
];

export const SEED_EVENTS: HistoricalEvent[] = [
  { id: 'great-pyramid', title: 'Great Pyramid of Giza', description: 'Construction of the Great Pyramid, one of the Seven Wonders of the Ancient World. Built as a tomb for Pharaoh Khufu, it stood 146.5 meters tall — the tallest human-made structure for over 3,800 years.', year: -2560, endYear: -2540, eraId: 'ancient', latitude: 29.9792, longitude: 31.1342, category: 'construction' },
  { id: 'code-hammurabi', title: 'Code of Hammurabi', description: 'One of the oldest known written legal codes, established by the Babylonian king Hammurabi. It contains 282 laws covering trade, property, family, and labor — an extraordinary window into ancient society.', year: -1754, eraId: 'ancient', latitude: 32.5421, longitude: 44.4209, category: 'political' },
  { id: 'trojan-war', title: 'Trojan War', description: 'The legendary conflict between the Greeks and the city of Troy, immortalized in Homer\'s Iliad. Whether myth or history, it shaped the cultural identity of the ancient Mediterranean world.', year: -1200, eraId: 'ancient', latitude: 39.9575, longitude: 26.2389, category: 'war' },
  { id: 'founding-rome', title: 'Founding of Rome', description: 'According to legend, Romulus founded Rome after killing his twin brother Remus. The city would grow to become the center of one of the largest empires in history.', year: -753, eraId: 'ancient', latitude: 41.9028, longitude: 12.4964, category: 'political' },
  { id: 'democracy-athens', title: 'Birth of Democracy', description: 'Cleisthenes introduces democratic reforms in Athens, establishing the world\'s first known democracy. Citizens could vote directly on legislation and executive bills.', year: -508, eraId: 'classical', latitude: 37.9838, longitude: 23.7275, category: 'political' },
  { id: 'roman-forum', title: 'Roman Forum Inauguration', description: 'The Roman Forum becomes the center of Roman public life — hosting triumphal processions, elections, public speeches, and commercial affairs for centuries.', year: -500, eraId: 'classical', latitude: 41.8925, longitude: 12.4853, category: 'cultural' },
  { id: 'alexander-empire', title: 'Alexander the Great\'s Empire', description: 'At just 30 years old, Alexander had created one of the largest empires in history, stretching from Greece to northwestern India.', year: -323, eraId: 'classical', latitude: 40.6401, longitude: 22.9444, category: 'political' },
  { id: 'great-wall-begin', title: 'Great Wall Construction Begins', description: 'Emperor Qin Shi Huang orders the connection and extension of existing walls to protect against northern invasions. The wall would eventually span over 21,000 kilometers.', year: -221, eraId: 'classical', latitude: 40.4319, longitude: 116.5704, category: 'construction' },
  { id: 'julius-caesar', title: 'Assassination of Julius Caesar', description: 'On the Ides of March, Julius Caesar is assassinated by a group of senators, triggering the end of the Roman Republic and the rise of the Roman Empire.', year: -44, eraId: 'classical', latitude: 41.8955, longitude: 12.4823, category: 'political' },
  { id: 'colosseum', title: 'Colosseum Completed', description: 'The Colosseum is completed under Emperor Titus. Capable of holding 50,000-80,000 spectators, it hosted gladiatorial contests, public spectacles, and dramas.', year: 80, eraId: 'classical', latitude: 41.8902, longitude: 12.4922, category: 'construction' },
  { id: 'fall-of-rome', title: 'Fall of the Western Roman Empire', description: 'The last Western Roman Emperor, Romulus Augustulus, is deposed by the Germanic chieftain Odoacer, marking the traditional end of the ancient world.', year: 476, eraId: 'classical', latitude: 41.9028, longitude: 12.4964, category: 'political' },
  { id: 'hagia-sophia', title: 'Hagia Sophia Completed', description: 'Emperor Justinian I completes the Hagia Sophia in Constantinople. For nearly a thousand years, it was the largest cathedral in the world.', year: 537, eraId: 'medieval', latitude: 41.0086, longitude: 28.9802, category: 'construction' },
  { id: 'viking-expansion', title: 'Viking Expansion Begins', description: 'Norse warriors raid Lindisfarne monastery in England, marking the beginning of the Viking Age — an era of exploration, trade, and conquest spanning three centuries.', year: 793, eraId: 'medieval', latitude: 55.6689, longitude: -1.7847, category: 'war' },
  { id: 'genghis-khan', title: 'Mongol Empire Founded', description: 'Genghis Khan unites the Mongol tribes and begins building the largest contiguous land empire in history, stretching from Korea to Eastern Europe.', year: 1206, eraId: 'medieval', latitude: 47.9184, longitude: 106.9177, category: 'political' },
  { id: 'black-death', title: 'The Black Death', description: 'The bubonic plague devastates Europe, killing an estimated 30-60% of the population. It fundamentally transforms European society, economy, and culture.', year: 1347, eraId: 'medieval', latitude: 43.7696, longitude: 11.2558, category: 'natural' },
  { id: 'gutenberg-press', title: 'Gutenberg Printing Press', description: 'Johannes Gutenberg invents the movable-type printing press, revolutionizing the spread of knowledge and laying the groundwork for the Renaissance and Reformation.', year: 1440, eraId: 'medieval', latitude: 49.9929, longitude: 8.2473, category: 'discovery' },
  { id: 'columbus-americas', title: 'Columbus Reaches the Americas', description: 'Christopher Columbus lands in the Bahamas, initiating sustained European contact with the Americas and forever changing the course of world history.', year: 1492, eraId: 'renaissance', latitude: 24.0667, longitude: -74.5167, category: 'discovery' },
  { id: 'manhattan-purchase', title: 'Purchase of Manhattan', description: 'Peter Minuit purchases Manhattan Island from the Lenape for 60 guilders. The island would become New York City, one of the most influential cities in modern history.', year: 1626, eraId: 'renaissance', latitude: 40.7128, longitude: -74.0060, category: 'political' },
  { id: 'french-revolution', title: 'French Revolution', description: 'The storming of the Bastille marks the beginning of the French Revolution, which would overthrow the monarchy and reshape political thought worldwide.', year: 1789, eraId: 'renaissance', latitude: 48.8532, longitude: 2.3692, category: 'political' },
  { id: 'steam-locomotive', title: 'First Steam Locomotive', description: 'Richard Trevithick demonstrates the first full-scale working railway steam locomotive in Wales, launching the railway age.', year: 1804, eraId: 'industrial', latitude: 51.7507, longitude: -3.3791, category: 'discovery' },
  { id: 'suez-canal', title: 'Suez Canal Opens', description: 'The Suez Canal opens, connecting the Mediterranean and Red Seas. It revolutionizes global trade by dramatically reducing shipping times between Europe and Asia.', year: 1869, eraId: 'industrial', latitude: 30.4574, longitude: 32.3499, category: 'construction' },
  { id: 'eiffel-tower', title: 'Eiffel Tower Completed', description: 'Gustave Eiffel completes the iron lattice tower for the 1889 World\'s Fair. At 300 meters, it was the tallest structure in the world until 1930.', year: 1889, eraId: 'industrial', latitude: 48.8584, longitude: 2.2945, category: 'construction' },
  { id: 'ww1', title: 'World War I Begins', description: 'The assassination of Archduke Franz Ferdinand triggers a chain of alliances that plunges Europe into the first global industrial war, killing over 17 million people.', year: 1914, eraId: 'modern', latitude: 48.2082, longitude: 16.3738, category: 'war' },
  { id: 'ww2', title: 'World War II Begins', description: 'Germany invades Poland, beginning the deadliest conflict in human history. Over 70 million people would perish before its end in 1945.', year: 1939, eraId: 'modern', latitude: 52.2297, longitude: 21.0122, category: 'war' },
  { id: 'moon-landing', title: 'Moon Landing', description: 'Apollo 11 astronauts Neil Armstrong and Buzz Aldrin become the first humans to walk on the Moon. "That\'s one small step for man, one giant leap for mankind."', year: 1969, eraId: 'modern', latitude: 28.5721, longitude: -80.6480, category: 'discovery' },
  { id: 'berlin-wall', title: 'Fall of the Berlin Wall', description: 'The Berlin Wall falls, symbolizing the end of the Cold War and the beginning of German reunification. It marks a turning point in world history.', year: 1989, eraId: 'modern', latitude: 52.5163, longitude: 13.3777, category: 'political' },
  { id: 'www-invention', title: 'World Wide Web Invented', description: 'Tim Berners-Lee proposes the World Wide Web at CERN, creating the foundation for the modern internet and transforming virtually every aspect of human society.', year: 1989, eraId: 'modern', latitude: 46.2044, longitude: 6.1432, category: 'discovery' },
];

export const LOCATIONS: Location[] = [
  { id: 'egypt', name: 'Giza, Egypt', country: 'Egypt', latitude: 29.9792, longitude: 31.1342, description: 'Home of the Great Pyramids and the Sphinx, the last surviving Wonder of the Ancient World.', defaultZoom: 6, availableEras: ['ancient', 'classical', 'medieval', 'renaissance', 'industrial', 'modern'] },
  { id: 'rome', name: 'Rome, Italy', country: 'Italy', latitude: 41.9028, longitude: 12.4964, description: 'The Eternal City — center of the Roman Republic, the Roman Empire, and the Catholic Church.', defaultZoom: 6, availableEras: ['classical', 'medieval', 'renaissance', 'industrial', 'modern'] },
  { id: 'athens', name: 'Athens, Greece', country: 'Greece', latitude: 37.9838, longitude: 23.7275, description: 'Birthplace of democracy, Western philosophy, and the Olympic Games.', defaultZoom: 6, availableEras: ['classical', 'medieval', 'modern'] },
  { id: 'newYork', name: 'New York, USA', country: 'United States', latitude: 40.7128, longitude: -74.0060, description: 'From Dutch trading post to global metropolis — a city that defines the modern world.', defaultZoom: 6, availableEras: ['renaissance', 'industrial', 'modern'] },
  { id: 'beijing', name: 'Beijing, China', country: 'China', latitude: 39.9042, longitude: 116.4074, description: 'Imperial capital for centuries, home of the Forbidden City and the Great Wall.', defaultZoom: 5, availableEras: ['ancient', 'classical', 'medieval', 'renaissance', 'industrial', 'modern'] },
  { id: 'paris', name: 'Paris, France', country: 'France', latitude: 48.8566, longitude: 2.3522, description: 'The City of Light — epicenter of the Enlightenment, Revolution, and modern art.', defaultZoom: 6, availableEras: ['medieval', 'renaissance', 'industrial', 'modern'] },
  { id: 'istanbul', name: 'Istanbul, Turkey', country: 'Turkey', latitude: 41.0082, longitude: 28.9784, description: 'Constantinople — the crossroads of Europe and Asia, capital of two great empires.', defaultZoom: 6, availableEras: ['classical', 'medieval', 'renaissance', 'modern'] },
  { id: 'mesopotamia', name: 'Babylon, Iraq', country: 'Iraq', latitude: 32.5421, longitude: 44.4209, description: 'The cradle of civilization — where writing, law, and urban life were born.', defaultZoom: 5, availableEras: ['prehistory', 'ancient', 'classical'] },
  { id: 'london', name: 'London, UK', country: 'United Kingdom', latitude: 51.5074, longitude: -0.1278, description: 'From Roman Londinium to the capital of the British Empire, a city at the heart of world events.', defaultZoom: 6, availableEras: ['classical', 'medieval', 'renaissance', 'industrial', 'modern'] },
  { id: 'mongolia', name: 'Karakorum, Mongolia', country: 'Mongolia', latitude: 47.9184, longitude: 106.9177, description: 'Capital of the Mongol Empire, the largest contiguous land empire in history.', defaultZoom: 4, availableEras: ['medieval'] },
];

export const LANDMARKS: Landmark[] = [
  {
    id: 'pyramids-giza',
    name: 'Pyramids of Giza',
    locationId: 'egypt',
    latitude: 29.9792,
    longitude: 31.1342,
    triggerZoom: 5.0,
    triggerRadius: 1100,
    timePeriods: [
      { name: 'construction', startYear: -2580, endYear: -2560, riveFile: '/assets/rive/pyramid_building.riv', label: 'Construction of the Pyramids' },
      { name: 'completed', startYear: -2560, endYear: 2024, riveFile: '/assets/rive/pyramid_finished.riv', label: 'Pyramids of Giza' },
    ],
  },
  {
    id: 'colosseum-rome',
    name: 'Colosseum',
    locationId: 'rome',
    latitude: 41.8902,
    longitude: 12.4922,
    triggerZoom: 5.0,
    triggerRadius: 1100,
    timePeriods: [
      { name: 'construction', startYear: 72, endYear: 80, riveFile: '/assets/rive/colosseum.riv', label: 'Construction of the Colosseum' },
      { name: 'completed', startYear: 80, endYear: 2024, riveFile: '/assets/rive/colosseum.riv', label: 'The Colosseum' },
    ],
  },
];

export const BOUNDARY_YEAR_MAP: Record<number, string> = {
  [-10000]: 'world_bc10000',
  [-8000]: 'world_bc8000',
  [-5000]: 'world_bc5000',
  [-4000]: 'world_bc4000',
  [-3000]: 'world_bc3000',
  [-2000]: 'world_bc2000',
  [-1500]: 'world_bc1500',
  [-1000]: 'world_bc1000',
  [-700]: 'world_bc700',
  [-500]: 'world_bc500',
  [-400]: 'world_bc400',
  [-323]: 'world_bc323',
  [-300]: 'world_bc300',
  [-200]: 'world_bc200',
  [-100]: 'world_bc100',
  [-1]: 'world_bc1',
  100: 'world_100',
  200: 'world_200',
  300: 'world_300',
  400: 'world_400',
  500: 'world_500',
  600: 'world_600',
  700: 'world_700',
  800: 'world_800',
  900: 'world_900',
  1000: 'world_1000',
  1100: 'world_1100',
  1200: 'world_1200',
  1279: 'world_1279',
  1300: 'world_1300',
  1400: 'world_1400',
  1492: 'world_1492',
  1500: 'world_1500',
  1530: 'world_1530',
  1600: 'world_1600',
  1650: 'world_1650',
  1700: 'world_1700',
  1715: 'world_1715',
  1783: 'world_1783',
  1800: 'world_1800',
  1815: 'world_1815',
  1880: 'world_1880',
  1900: 'world_1900',
  1914: 'world_1914',
  1920: 'world_1920',
  1930: 'world_1930',
  1938: 'world_1938',
  1945: 'world_1945',
  1960: 'world_1960',
  1994: 'world_1994',
  2000: 'world_2000',
  2010: 'world_2010',
};
